---
title: "Ben Eppinger's Publications"
author: A guide to finding the right publication when citing Ben's work.
output:
  prettydoc::html_pretty:
    theme: cayman
---

## 2021

Eppinger, B., Goschke, T., & Musslick, S. (2021). Meta-control: From psychology to computational neuroscience. *Cognitive, affective & behavioral neuroscience*, 21*(3)*, 447–452. https://doi.org/10.3758/s13415-021-00919-4 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_35.pdf)

Reiter, A. M., Diaconescu, A. O., Eppinger, B., & Li, S. C. (2021). Human aging alters social inference about others’ changing intentions. *Neurobiology of Aging*, 103, 98–108. https://doi.org/10.1016/j.neurobiolaging.2021.01.034 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_34.pdf)

Ruel, A., Devine, S., & Eppinger, B. (2021). Resource-rational approach to meta-control problems across the lifespan. *Wiley interdisciplinary reviews. Cognitive science*, e1556. Advance online publication. https://doi.org/10.1002/wcs.1556 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_33.pdf)

Ruel, A., Bolenz, F., Li, S., Fischer, A. G., & Eppinger, B. (2021, April 23; **Under Review**). Neural evidence for age-related deficits in the representation of state spaces. *PsyArXiv*, https://doi.org/10.31234/osf.io/nh5u7

## 2020

Bolenz, F., Profitt, M. F., Stechbarth, F., Eppinger, B., & Strobel, A. (2020, June 10; **Under Review**). Need for cognition does not account for individual differences in metacontrol of decision making. *PsyArXiv*, https://doi.org/10.31234/osf.io/d7y4w

Bolenz F, Eppinger, B. (2020, October 7; **Submission**) Valence bias in metacontrol of decision making in adolescents and young adults. *PsyArXiv*, https://doi.org/10.31234/osf.io/5u9jq

Bruckner, R., Nassar, M. R., Li, S., & Eppinger, B. (2020, July 29; **Under Review**). Differences in adaptive learning across the lifespan are driven by satisficing. *PsyArXiv*, https://doi.org/10.31234/osf.io/nh9bq 

Devine, S., Neumann, C., Levari, D., Wilson, R. C., & Eppinger, B. (2020, July 27; **Under Review**). Human ageing is associated with more rigid concept spaces. *Proceedings of the 42nd Annual Meeting of the Cognitive Science Society.*, https://doi.org/10.31234/osf.io/uhcp7 [[pdf]](http://www.ldmlab.org/images/Devineetal2020_NHB.pdf)

## 2019

Bolenz, F., Kool, W., Reiter, A. M., & Eppinger, B. (2019). Metacontrol of decision-making strategies in human aging. *eLife*, *8*, e49154. https://doi.org/10.7554/eLife.49154 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_32.pdf)

Devine, S., Otto, A. R., Bolenz, F., Reiter, A. M., & Eppinger, B. (2019, December 9; **Under Review**). Cognitive resource limitations shift effort trade-offs across the lifespan. *PsyArXiv*, https://doi.org/10.31234/osf.io/9m6au  

Kroemer, N. B., Lee, Y., Pooseh, S., Eppinger, B., Goschke, T., & Smolka, M. N. (2019). L-DOPA reduces model-free control of behavior by attenuating the transfer of value to action. *Neuroimage*, 186, 113–125. https://doi.org/10.1016/j.neuroimage.2018.10.075 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_31.pdf)

Reiter, A. M., Suzuki, S., O'Doherty, J. P., Li, S. C., & Eppinger, B. (2019). Risk contagion by peers affects learning and decision-making in adolescents. *Journal of experimental psychology: general*, *148*(9), 1494–1504. https://doi.org/10.1037/xge0000512 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_30.pdf)

## 2018

Rodriguez Buritica, J. M., Heekeren, H. R., Li, S. C., & Eppinger, B. (2018). Developmental differences in the neural dynamics of observational learning. *Neuropsychologia*, 119, 12–23. https://doi.org/10.1016/j.neuropsychologia.2018.07.022 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_29.pdf)

van den Bos, W., Bruckner, R., Nassar, M. R., Mata, R., & Eppinger, B. (2018). Computational neuroscience across the lifespan: Promises and pitfalls. *Developmental cognitive neuroscience*, 33, 42–53. https://doi.org/10.1016/j.dcn.2017.09.008 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_28.pdf)

Wittkuhn, L., Eppinger, B., Bartsch, L. M., Thurm, F., Korb, F. M., & Li, S. C. (2018). Repetitive transcranial magnetic stimulation over dorsolateral prefrontal cortex modulates value-based learning during sequential decision-making. *NeuroImage*, 167, 384–395. https://doi.org/10.1016/j.neuroimage.2017.11.057 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_27.pdf)

Eppinger, B., Heekeren, H. R., & Li, S. C. (2018). Age Differences in the Neural Mechanisms of Intertemporal Choice Under Subjective Decision Conflict. *Cerebral cortex*, *28*(11), 3764–3774. https://doi.org/10.1093/cercor/bhx239 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_26.pdf)

## 2017

Eppinger, B., Walter, M., & Li, S. C. (2017). Electrophysiological correlates reflect the integration of model-based and model-free decision information. *Cognitive, affective & behavioral neuroscience*, *17*(2), 406–421. https://doi.org/10.3758/s13415-016-0487-3 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_25.pdf)

Bolenz, F., Reiter, A., & Eppinger, B. (2017). Developmental Changes in Learning: Computational Mechanisms and Social Influences. *Frontiers in psychology*, *8*, 2048. https://doi.org/10.3389/fpsyg.2017.02048 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_24.pdf)

Reiter, A., Kanske, P., Eppinger, B., & Li, S. C. (2017). The Aging of the Social Mind - Differential Effects on Components of Social Understanding. *Scientific reports*, *7*(1), 11046. https://doi.org/10.1038/s41598-017-10669-4 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_23.pdf)

## 2016

Rodriguez Buritica, J. M., Eppinger, B., Schuck, N. W., Heekeren, H. R., & Li, S. C. (2016). Electrophysiological correlates of observational learning in children. *Developmental science*, *19*(5), 699–709. https://doi.org/10.1111/desc.12317 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_22.pdf)

van den Bos, W., & Eppinger, B. (2016). Developing developmental cognitive neuroscience: From agenda setting to hypothesis testing. *Developmental cognitive neuroscience*, *17*, 138–144. https://doi.org/10.1016/j.dcn.2015.12.011 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_21.pdf)

Nassar, M. R., Bruckner, R., & Eppinger, B. (2016). What do we GANE with age?. *Behavioral and brain sciences*, *39*, e218. https://doi.org/10.1017/S0140525X15001892  [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_20.pdf)

Nassar, M. R., Bruckner, R., Gold, J. I., Li, S. C., Heekeren, H. R., & Eppinger, B. (2016). Age differences in learning emerge from an insufficient representation of uncertainty in older adults. *Nature communications*, *7*, 11609. https://doi.org/10.1038/ncomms11609  [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_19.pdf)

Li, S.-C., & Eppinger, B. (2016). Lifespan development of adaptive neurocognitive representations: Reciprocal interactions between cognition and motivation. In T. Braver (Ed.), *Handbook of Motivation and Control* (pp. 283–311). *Academic Press*.  [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_18.pdf) 

## 2015–2005

Eppinger, B., & Bruckner, R. (2015). Towards a mechanistic understanding of age-related changes in learning and decision making: A neuro-computational approach. In T. M. Hess, J. Strough., & C. E. Löckenhoff (Eds.), *Aging and Decision Making: empirical and applied perspectives* (pp. 61–77). *Academic Press*. [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_17.pdf)

Eppinger, B., Heekeren, H. R., & Li, S. C. (2015). Age-related prefrontal impairments implicate deficient prediction of future reward in older adults. *Neurobiology of aging*, *36*(8), 2380–2390. https://doi.org/10.1016/j.neurobiolaging.2015.04.010 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_16.pdf)

Störmer, V., Eppinger, B. & Li, S. C. (2014) Reward speeds up and increases consistency of visual selective attention: a lifespan comparison. *Cognitive, Affective & Behavioral Neuroscience*, 14, 659–671. https://doi.org/10.3758/s13415-014-0273-z [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_15.pdf)

Eppinger, B., Schuck, N. W., Nystrom, L. E., & Cohen, J. D. (2013). Reduced striatal responses to reward prediction errors in older compared with younger adults. *Journal of Neuroscience*, *33*(24), 9905–9912. https://doi.org/10.1523/JNEUROSCI.2942-12.2013 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_14.pdf)

Eppinger, B., Walter, M., Heekeren, H. R., & Li, S. C. (2013). Of goals and habits: age-related and individual differences in goal-directed decision-making. *Frontiers in neuroscience*, *7*, 253. https://doi.org/10.3389/fnins.2013.00253 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_13.pdf)

Hämmerer, D., & Eppinger, B. (2012). Dopaminergic and prefrontal contributions to reward-based learning and outcome monitoring during child development and aging. *Developmental psychology*, *48*(3), 862–874. https://doi.org/10.1037/a0027342 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_12.pdf)

Eppinger, B., Nystrom, L. E., & Cohen, J. D. (2012). Reduced sensitivity to immediate reward during decision-making in older than younger adults. *PloS one*, *7*(5), e36953. https://doi.org/10.1371/journal.pone.0036953 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_11.pdf)

Eppinger, B., & Kray, J. (2011). To choose or to avoid: age differences in learning from positive and negative feedback. *Journal of Cognitive Neuroscience*, *23*(1), 41–52. https://doi.org/10.1162/jocn.2009.21364 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_10.pdf)

Herbert, M., Eppinger, B., & Kray, J. (2011). Younger but not older adults benefit from salient feedback during learning. *Frontiers in psychology*, *2*, 171. https://doi.org/10.3389/fpsyg.2011.00171 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_09.pdf)

Eppinger, B., Hämmerer, D., & Li, S. C. (2011). Neuromodulation of reward-based learning and decision making in human aging. *Annals of the New York Academy of Sciences*, 1235, 1. https://doi.org/10.1111/j.1749-6632.2011.06230.x [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_08.pdf)

Eppinger, B., Herbert, M., & Kray, J. (2010). We remember the good things: Age differences in learning and memory. *Neurobiology of Learning and Memory*, *93*(4), 515–521. https://doi.org/10.1016/j.nlm.2010.01.009 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_07.pdf)

Kray, J., & Eppinger, B. (2009). An event-related potential (ERP) approach to study cognitive control processes. In M. Crocker & J. Siekmann (Eds.), Resource-adaptive cognitive processes (pp. 77–94). *Springer*. [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_06.pdf)

Eppinger, B. , Mock, B., & Kray, J. (2009). Developmental differences in learning and error processing: evidence from ERPs. *Psychophysiology*, *46*(5), 1043–1053. https://doi.org/10.1111/j.1469-8986.2009.00838.x [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_05.pdf)

Eppinger, B. , Kray, J., Mock, B., & Mecklinger, A. (2008). Better or worse than expected? Aging, learning, and the ERN. *Neuropsychologia*, *46*(2), 521–539. https://doi.org/10.1016/j.neuropsychologia.2007.09.001 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_04.pdf)

Eppinger, B. , Kray, J., Mecklinger, A., & John, O. (2007). Age differences in task switching and response monitoring: Evidence from ERPs. *Biological Psychology*, *75*(1), 52–67. https://doi.org/10.1016/j.biopsycho.2006.12.001 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_03.pdf)

Kray, J., & Eppinger, B. (2006). Effects of associative learning on age differences in task-set switching. *Acta Psychologica*, *123*(3), 187–203. https://doi.org/10.1016/j.actpsy.2005.12.009 [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_02.pdf)

Kray, J., Eppinger, B., & Mecklinger, A. (2005). Age differences in attentional control: An event‐related potential approach. *Psychophysiology*, *42*(4), 407–416. https://doi.org/10.1111/j.1469-8986.2005.00298.x [[pdf]](https://github.com/LDMLab/LDMLab.github.io/blob/master/pdf_publications/BE_01.pdf)


# Abstract of each publication

| Title(**Year**)     | Abstract |
| --- | ----------------- |
| Meta-control: From psychology to computational neuroscience. (**2021**), Article.| <sub><sup>Research in the past decades shed light on the different mechanisms that underlie our capacity for cognitive control. However, the meta-level processes that regulate cognitive control itself remain poorly understood. Following the terminology from artificial intelligence, meta-control can be defined as a collection of mechanisms that (a) monitor the progress of controlled processing and (b) regulate the underlying control parameters in the service of current task goals and in response to internal or external constraints. From a psychological perspective, meta-control is an important concept because it may help explain and predict how and when human agents select different types of behavioral strategies. From a cognitive neuroscience viewpoint, meta-control is a useful concept for understanding the complex networks in the prefrontal cortex that guide higher-level behavior as well as their interactions with neuromodulatory systems (such as the dopamine or norepinephrine system). The purpose of the special issue is to integrate hitherto segregated strands of research across three different perspectives: 1) a psychological perspective that specifies meta-control processes on a functional level and aims to operationalize them in experimental tasks; 2) a computational perspective that builds on ideas from artificial intelligence to formalize normative solutions to meta-control problems; and 3) a cognitive neuroscience perspective that identifies neural correlates of and mechanisms underlying meta-control.</sup></sub>|
| Human aging alters social inference about others' changing intentions. (**2021**), Article.| <sub><sup>Decoding others' intentions accurately in order to adapt one's own behavior is pivotal throughout life. In this study, we asked how younger and older adults deal with uncertainty in dynamic social environments. We used an advice-taking paradigm together with Bayesian modeling to characterize effects of aging on learning about others' time-varying intentions. We observed age differences when comparing learning on two levels of social uncertainty: the fidelity of the adviser and the volatility of intentions. Older adults expected the adviser to change his/her intentions more frequently (i.e., a higher volatility of the adviser). They also showed higher confidence (i.e., precision) in their volatility beliefs and were less willing to change their beliefs about volatility over the course of the experiment. This led them to update their predictions about the fidelity of the adviser more quickly. Potentially indicative of stereotype effects, we observed that older advisers were perceived as more volatile, but also more faithful than younger advisers. This offers new insights into adult age differences in response to social uncertainty.</sup></sub>|
| Resource-rational approach to meta-control problems across the lifespan. (**2021**), Advance online publication.| <sub><sup>Over the last decade, research on cognitive control and decision-making has revealed that individuals weigh the costs and benefits of engaging in or refraining from control and that whether and how they engage in these cost/benefit analyses may change across development and during healthy aging. In the present article, we examine how lifespan age differences in cognitive abilities affect the meta-control of behavioral strategies across the lifespan and how motivation affects these trade-offs. Based on accumulated evidence, we highlight two hypotheses that may explain the existing results better than current models. In contrast to previous theoretical accounts, we assume that age differences in the engagement in cost/benefit trade-offs reflect a resource-rational adaptation to internal and external constraints that arise across the lifespan.</sup></sub>|
| Neural evidence for age-related deficits in the representation of state spaces. (**2021**), Preprint.| <sub><sup>When under high cognitive demand older adults tend to resort to simpler, model-free decision strategies. This age-related shift in decision behaviour has been attributed to deficits in the representation of the cognitive maps, or state spaces, necessary for more complex model-based decision-making. Yet, the neural mechanism behind this shift remains unclear. We analysed performance on a modified two-stage Markov task using a novel neurocomputational approach including computational modeling and single-trial EEG analyses to establish neural markers of age-related changes in goal-directed decision-making under different representational demands. Our results reveal that the shift to simpler decision strategies in older adults is due a) impairments in the representation of the transition structure of the task and b) a diminished signaling of the reward value associated with decision options. Consistent with the diminished state space hypothesis of human aging, our findings reveal that deficits in goal-directed, model-based behavior in older adults results from impairments in the representation of state spaces of cognitive tasks.</sup></sub>|
| Need for cognition does not account for individual differences in metacontrol of decision making. (**2020**), Preprint.| <sub><sup>Humans show metacontrol of decision-making towards different reward magnitudes. Specifically, when higher rewards are at stake, individuals increase reliance on a more accurate but cognitively effortful strategy. We investigated whether the personality trait Need for Cognition (NFC) explains individual differences in metacontrol. Based on findings of cognitive effort expenditure in executive functions, we expected more metacontrol in individuals low in NFC. In two independent studies, metacontrol was assessed by means of a decision-making task that dissociates different reinforcement-learning strategies. In contrast to our expectations, NFC did not account for individual differences in metacontrol of decision making. These findings suggest a differential role of NFC for the regulation of cognitive effort in decision making and executive functions.</sup></sub>|
| Valence bias in metacontrol of decision making in adolescents and young adults. (**2020**), Preprint.| <sub><sup>Metacontrol refers to the human ability to dynamically adapt decision-making strategies to changes in internal and external demands. In this study, we investigated the development of metacontrol from adolescence into young adulthood as well as developmental differences in the sensitivity of metacontrol to framing effects. Adolescents and young adults were assessed with a decision-making task that dissociates model-free and model-based decision-making strategies. In this task, we manipulated outcome magnitude and outcome valence, i.e. the framing of outcomes. With increasing age, we found a greater adaptation of model-based decision making to outcome magnitudes. Model-based decision making was more pronounced for loss compared to gain frames but this framing effect did not differ with age. Our findings suggest that metacontrol continues to develop into young adulthood. While losses generally increase the motivation to invest cognitive resources into an effortful decision-making strategy, the development of metacontrol is not sensitive to framing effects.</sup></sub>|
| Differences in adaptive learning across the lifespan are driven by satisficing. (**2020**), Preprint.| <sub><sup>Learning is pervasive across the human lifespan and essential for adaptive behavior. Children and older adults are often slower to learn cognitive tasks than young adults. Here we build on established theory formalizing learning as predictive inference and consider the possibility that age-related learning differences emerge from satisficing in this prediction problem - that is, accepting predictions that achieve some sufficient level of accuracy. In our computational formalization of this idea, beliefs are updated through an active process until reaching some criterion value of acceptability, which is set more liberally in children and older adults. In line with our model's predictions, children and older adults showed frequent perseveration when asked to update beliefs from their previous values but were also more highly influenced by environmental manipulations of the starting value from which beliefs are updated. Our model and results provide a unifying perspective on seemingly contradictory findings showing developmental differences in the reliance on internal and external behavioral biases by suggesting that they both emerge from a liberal satisficing policy.</sup></sub>|
| Human ageing is associated with more rigid concept spaces. (**2020**), Preprint.| <sub><sup> Prevalence-induced concept change describes a cognitive mechanism by which someone’s definition of a concept shifts as the prevalence of instances of that concept changes. While this phenomenon has been established in young adults, it is unclear how it affects older adults. In this study, we explore how prevalence-induced concept change affects older adults’ lower-level, perceptual, and higher-order, ethical, judgement and decision-making. We find that older adults are less sensitive to prevalence-induced concept change than younger adults across both domains. Using computational modeling, we demonstrate that these age-related changes in judgements reflect more cautious and deliberate responding in older adults. Based on these findings, we argue that while overly cautious responding may be maladaptive in some cognitive domains, in the case of prevalence-induced concept change, it can be protective against biased decision-making.</sup></sub>|
| Metacontrol of decision-making strategies in human aging. (**2019**), Article.| <sub><sup>Humans employ different strategies when making decisions. Previous research has reported reduced reliance on model-based strategies with aging, but it remains unclear whether this is due to cognitive or motivational factors. Moreover, it is not clear how aging affects the metacontrol of decision making, that is the dynamic adaptation of decision-making strategies to varying situational demands. In this cross-sectional study, we tested younger and older adults in a sequential decision-making task that dissociates model-free and model-based strategies. In contrast to previous research, model-based strategies led to higher payoffs. Moreover, we manipulated the costs and benefits of model-based strategies by varying reward magnitude and the stability of the task structure. Compared to younger adults, older adults showed reduced model-based decision making and less adaptation of decision-making strategies. Our findings suggest that aging affects the metacontrol of decision-making strategies and that reduced model-based strategies in older adults are due to limited cognitive abilities. </sup></sub>|
| Cognitive resource limitations shift effort trade-offs across the lifespan. (**2019**), Preprint.| <sub><sup> Previous work suggests that lifespan developmental differences in cognitive control abilities might be due to maturational and aging-related changes in prefrontal cortex functioning. However, there are other explanations: For example, it could be that children and older adults differ from younger adults in how they balance the effort of engaging in control against its potential benefits. In this work, we assume that the degree of engagement in cognitive effort depends on the opportunity cost of time (average reward rate per unit time). If the average reward rate is high, participants should speed up responding whereas if it is low, they should respond more slowly. Developmental changes in opportunity cost assessments may lead to differences in the sensitivity to changes in reward rate. To examine this hypothesis in children, adolescents, younger, and older adults, we applied a reward rate manipulation in two well-established cognitive control tasks: a modified Erikson Flanker and a task-switching paradigm. We found a significant interaction between age group and average reward rate, such that older adults were more sensitive to the average reward rate than the other age groups. However, as task complexity increased (from the Flanker task to the task-switching paradigm), children also became sensitive to changes in reward rate. This may suggest that when demands on cognitive load reach capacity limitations, participants engage in strategic behaviour to optimize performance: a view we present as the “sweet spot” argument of effort allocation. </sup></sub>|
| L-DOPA reduces model-free control of behavior by attenuating the transfer of value to action. (**2019**), Article.| <sub><sup> Dopamine is a key neurotransmitter in action control. However, influential theories of dopamine function make conflicting predictions about the effect of boosting dopamine neurotransmission. Here, we tested if increases in dopamine tone by administration of L-DOPA upregulate reward learning as predicted by reinforcement learning theories, and if increases are specific for deliberative, model-based control or reflexive, model-free control. Alternatively, L-DOPA may impair learning as suggested by, value or, thrift theories of dopamine. To this end, we employed a two-stage Markov decision-task to investigate the effect of L-DOPA (randomized cross-over) on behavioral control while brain activation was measured using fMRI. L-DOPA led to attenuated model-free control of behavior as indicated by the reduced impact of reward on choice. Increased model-based control was only observed in participants with high working memory capacity. Furthermore, L-DOPA facilitated exploratory behavior, particularly after a stream of wins in the task. Correspondingly, in the brain, L-DOPA decreased the effect of reward at the outcome stage and when the next decision had to be made. Critically, reward-learning rates and prediction error signals were unaffected by L-DOPA, indicating that differences in behavior and brain response to reward were not driven by differences in learning. Taken together, our results suggest that L-DOPA reduces model-free control of behavior by attenuating the transfer of value to action. These findings provide support for the value and thrift accounts of dopamine and call for a refined integration of valuation and action signals in reinforcement learning models.  </sup></sub>|
| Risk contagion by peers affects learning and decision-making in adolescents. (**2019**), Article.| <sub><sup> Adolescence is a period of life in which social influences‚ particularly if they come from peers‚ play a critical role in shaping learning and decision preferences. Recent studies in adults show evidence of a risk contagion effect; that is, individual risk preferences are modulated by observing and learning from others'risk-related decisions. In this study, using choice data and computational modeling, we demonstrate stronger risk contagion in male adolescents when observing peers compared to nonpeers. This effect was only present when the observed peer showed risk-seeking preferences. Moreover, adolescents represented the peers'decisions better than those of adults. Intriguingly, the degree of peer-biased risk contagion in adolescents was positively associated with real-life social integration. Contrary to previous accounts, our data suggest that peer conformity during risky decision-making in adolescence is a socially motivated, deliberative process. Susceptibility to peer influence in adolescence might be adaptive, associated with higher degrees of social functioning. </sup></sub>|
| Developmental differences in the neural dynamics of observational learning. (**2018**), Article.| <sub><sup> Learning from vicarious experience is central for educational practice, but not well understood with respect to its ontogenetic development and underlying neural dynamics. In this age-comparative study we compared behavioral and electrophysiological markers of learning from vicarious and one's own experience in children (age 8'10) and young adults. Behaviorally both groups benefitted from integrating vicarious experience into their own choices however, adults learned much faster from social information than children. The electrophysiological results show learning-related changes in the P300 to experienced and observed rewards in adults, but not in children, indicating that adults were more efficient in integrating observed and experienced information during learning. In comparison to adults, children showed an enhanced FRN for observed and experienced feedback, indicating that they focus more on valence information than adults. Taken together, children compared to adults seem to be less able to rapidly assess the informational value of observed and experienced feedback during learning and consequently up-regulate their response to both, observed and experienced (particularly negative) feedback. When transferring the current findings to an applied context, educational practice should strengthen children's ability to use feedback information for learning and be particularly cautious with negative social feedback during supervised learning.  </sup></sub>|
| Computational neuroscience across the lifespan: Promises and pitfalls. (**2018**), Article.| <sub><sup> In recent years, the application of computational modeling in studies on age-related changes in decision making and learning has gained in popularity. One advantage of computational models is that they provide access to latent variables that cannot be directly observed from behavior. In combination with experimental manipulations, these latent variables can help to test hypotheses about age-related changes in behavioral and neurobiological measures at a level of specificity that is not achievable with descriptive analysis approaches alone. This level of specificity can in turn be beneficial to establish the identity of the corresponding behavioral and neurobiological mechanisms. In this paper, we will illustrate applications of computational methods using examples of lifespan research on risk taking, strategy selection and reinforcement learning. We will elaborate on problems that can occur when computational neuroscience methods are applied to data of different age groups. Finally, we will discuss potential targets for future applications and outline general shortcomings of computational neuroscience methods for research on human lifespan development. </sup></sub>|
| Repetitive transcranial magnetic stimulation over dorsolateral prefrontal cortex modulates value-based learning during sequential decision-making. (**2018**), Article.| <sub><sup> Adaptive behavior in daily life often requires the ability to acquire and represent sequential contingencies between actions and the associated outcomes. Although accumulating evidence implicates the role of dorsolateral prefrontal cortex (dlPFC) in complex value-based learning and decision-making, direct evidence for involvements of this region in integrating information across sequential decision states is still scarce. Using a 3-stage deterministic Markov decision task, here we applied offline, inhibitory low-frequency 1-Hz repetitive transcranial magnetic stimulation (rTMS) over the left dlPFC in young male adults (n = 31, mean age = 23.8 years, SD = 2.5 years) in a within-subject cross-over design to study the roles of this region in influencing value-based sequential decision-making. In two separate sessions, each participant received 1-Hz rTMS stimulation either over the left dlPFC or over the vertex. The results showed that transiently inhibiting the left dlPFC impaired choice accuracy, particularly in situations in which the acquisition of sequential transitions between decision states and temporally lagged action-outcome contingencies played a greater role. Estimating parameters of a diffusion model from behavioral choices, we found that the diffusion drift rate, which reflects the efficiency of information integration, was attenuated by the stimulation. Moreover, the effects of rTMS interacted with session: individuals who could not efficiently integrate information across sequential states in the first session due to disrupted dlPFC function also could not catch up in performance during the second session with those individuals who could learn sequential transitions with intact dlPFC function in the first session. Taken together, our findings suggest that the left dlPFC is crucially involved in the acquisition of complex sequential relations and in the potential of such learning. </sup></sub>|
| Age Differences in the Neural Mechanisms of Intertemporal Choice Under Subjective Decision Conflict. (**2018**), Article.| <sub><sup> Older decision-makers may capitalize on their greater experiences in financial decisions and by this offset decline in cognitive abilities. However, this pattern of results should reverse in situations that place high demands on cognitive control functions. In this study, we investigated how decision conflict affects the neural mechanisms of intertemporal decision-making in younger and older adults. To individually adjust the level of decision conflict we determined the indifference point (IDP) in intertemporal decision-making for each participant. During functional magnetic resonance imaging, participants performed choice options close to their IDP (high conflict) or far away from the IDP (low conflict). In younger adults, decision conflict leads to reduced delay discounting and lower discount rates are associated with higher working memory (WM) capacity. In older adults, high decision conflict is associated with enhanced discounting, hypoactivation in the ventral striatum as well diminished ventral striatal representations of differences in subjective values. Taken together, our results show that under enhanced decision conflict, younger adults engage in a more reflective decision mode that reflects individual differences in WM capacity. In contrast, older adults get more present-oriented under high demands on cognitive control and this decision bias is associated with changes in striatal value signaling. </sup></sub>|
| Electrophysiological correlates reflect the integration of model-based and model-free decision information. (**2017**), Article.| <sub><sup> In this study, we investigated the interplay of habitual (model-free) and goal-directed (model-based) decision processes by using a two-stage Markov decision task in combination with event-related potentials (ERPs) and computational modeling. To manipulate the demands on model-based decision making, we applied two experimental conditions with different probabilities of transitioning from the first to the second stage of the task. As we expected, when the stage transitions were more predictable, participants showed greater model-based (planning) behavior. Consistent with this result, we found that stimulus-evoked parietal (P300) activity at the second stage of the task increased with the predictability of the state transitions. However, the parietal activity also reflected model-free information about the expected values of the stimuli, indicating that at this stage of the task both types of information are integrated to guide decision making. Outcome-related ERP components only reflected reward-related processes: Specifically, a medial prefrontal ERP component (the feedback-related negativity) was sensitive to negative outcomes, whereas a component that is elicited by reward (the feedback-related positivity) increased as a function of positive prediction errors. Taken together, our data indicate that stimulus-locked parietal activity reflects the integration of model-based and model-free information during decision making, whereas feedback-related medial prefrontal signals primarily reflect reward-related decision processes. </sup></sub>|
| Developmental Changes in Learning: Computational Mechanisms and Social Influences. (**2017**), Article.| <sub><sup> Our ability to learn from the outcomes of our actions and to adapt our decisions accordingly changes over the course of the human lifespan. In recent years, there has been an increasing interest in using computational models to understand developmental changes in learning and decision-making. Moreover, extensions of these models are currently applied to study socio-emotional influences on learning in different age groups, a topic that is of great relevance for applications in education and health psychology. In this article, we aim to provide an introduction to basic ideas underlying computational models of reinforcement learning and focus on parameters and model variants that might be of interest to developmental scientists. We then highlight recent attempts to use reinforcement learning models to study the influence of social information on learning across development. The aim of this review is to illustrate how computational models can be applied in developmental science, what they can add to our understanding of developmental mechanisms and how they can be used to bridge the gap between psychological and neurobiological theories of development. </sup></sub>|
| The Aging of the Social Mind - Differential Effects on Components of Social Understanding. (**2017**), Article.| <sub><sup> Research in younger adults dissociates cognitive from affective facets of social information processing, rather than promoting a monolithic view of social intelligence. An influential theory on adult development suggests differential effects of aging on cognitive and affective functions. However, this dissociation has not been directly tested in the social domain. Employing a newly developed naturalistic paradigm that disentangles facets of the social mind within an individual, we show multi-directionality of age-related differences. Specifically, components of the socio-cognitive route – Theory of Mind and metacognition – are impaired in older relative to younger adults. Nevertheless, these social capacities are still less affected by aging than factual reasoning and metacognition regarding non-social content. Importantly, the socio-affective route is well-functioning, with no decline in empathy and elevated compassion in the elderly. These findings contribute to an integrated theory of age-related change in social functioning and inform interventions tailored to specifically reinstate socio-cognitive skills in old age. </sup></sub>|
| Electrophysiological correlates of observational learning in children. (**2016**), Article.| <sub><sup> Observational learning is an important mechanism for cognitive and social development. However, the neurophysiological mechanisms underlying observational learning in children are not well understood. In this study, we used a probabilistic reward-based observational learning paradigm to compare behavioral and electrophysiological markers of individual and observational reinforcement learning in 8- to 10-year-old children. Specifically, we manipulated the amount of observable information as well as children's similarity in age to the observed person (same-aged child vs. adult) to examine the effects of similarity in age on the integration of observed information in children. We show that the feedback-related negativity (FRN) during individual reinforcement learning reflects the valence of outcomes of own actions. Furthermore, we found that the feedback-related negativity during observational reinforcement learning (oFRN) showed a similar distinction between outcome valences of observed actions. This suggests that the oFRN can serve as a measure of observational learning in middle childhood. Moreover, during observational learning children profited from the additional social information and imitated the choices of their own peers more than those of adults, indicating that children have a tendency to conform more with similar others (e.g. their own peers) compared to dissimilar others (adults). Taken together, our results show that children can benefit from integrating observable information and that oFRN may serve as a measure of observational learning in children. </sup></sub>|
| Developing developmental cognitive neuroscience: From agenda setting to hypothesis testing. (**2016**), Article.| <sub><sup> In this issue of Developmental Cognitive Neuroscience Shulman and colleagues and Nelson and colleagues present two heuristic models of cognitive development. Shulman and colleagues review the current evidence in favor of dual systems (DS) models, which suggests that enhanced risk taking in adolescents is the consequence of an imbalance between an early maturing motivational system involved in reward processing and a later maturing cognitive control system. They conclude with the viewpoint that the current literature seems to reaffirm the usefulness of these models. In a similar fashion, Nelson and colleagues presented an updated version of the social information processing model (SIP), a heuristic framework which links facets of social development (ranging form infant caregiver interactions to intimate relationships during adolescence) with functional changes in the developing brain. In this comment we provide a critical review of heuristic models, making specific references to the DS and SIP models, focusing on their ability to move the field of developmental cognitive neuroscience forward toward a mechanistic understanding of neural development. We aim to make a contribution to the debate around models by (1) providing further conceptual clarification and a framework to evaluate different types of models, and (2) by highlighting the benefits of a stronger commitment to cognitive models in order to generate testable hypotheses and integrate different levels of analyses (including neuroscience). First, we discuss the role of heuristic models in science as frameworks for inspiration and research agenda setting. Although heuristic models are by nature simplistic, we will suggest several principles that can be used to evaluate them. Next we discuss one direction that could be taken to foster the transition from heuristic models to cognitive neuroscience models , from agenda setting to hypothesis testing. </sup></sub>|
| What do we GANE with age? (**2016**), Article.| <sub><sup> Mather and colleagues provide an impressive cross-level account of how arousal levels modulate behavior, and they support it with data ranging from receptor pharmacology to measures of cognitive function. Here we consider two related questions: (1) Why should the brain engage in different arousal levels? and (2) What are the predicted consequences of age-related changes in norepinephrine signaling for cognitive function? </sup></sub>|
| Age differences in learning emerge from an insufficient representation of uncertainty in older adults (**2016**), Article.| <sub><sup> Healthy aging can lead to impairments in learning that affect many laboratory and real-life tasks. These tasks often involve the acquisition of dynamic contingencies, which requires adjusting the rate of learning to environmental statistics. For example, learning rate should increase when expectations are uncertain (uncertainty), outcomes are surprising (surprise) or contingencies are more likely to change (hazard rate). In this study, we combine computational modelling with an age-comparative behavioural study to test whether age-related learning deficits emerge from a failure to optimize learning according to the three factors mentioned above. Our results suggest that learning deficits observed in healthy older adults are driven by a diminished capacity to represent and use uncertainty to guide learning. These findings provide insight into age-related cognitive changes and demonstrate how learning deficits can emerge from a failure to accurately assess how much should be learned. </sup></sub>|
| Lifespan development of adaptive neurocognitive representations: Reciprocal interactions between cognition and motivation. (**2016**), Book Chapter.| <sub><sup> Given that currently there is more convergent evidence relating lifespan differences in the effi cacy of dopaminergic modulation, this review focuses only on the contributions of dopamine to lifespan development of cognitive and motivational self-regulations as well as their interactions. However, the effects of other transmitter systems and how they interact with the dopamine system in modulating cognition and motivation need to be investigated more systematically. For instance, it has been proposed that the development of different cognitive control networks (e.g., alerting, orienting, executive attention) may be modulated by different neurotransmitter systems, with the orienting attention being modulated by the cholinergic system and executive attention being modulated by the dopamine system (Posner et al., 2012; Störmer et al., 2012). It has also been proposed that serotonin may interact with dopamine in regulating approach- and avoidance-associated motivational infl uences on actions (see Guitart-Masip, Duzel, Dolan, & Dayan, 2014, for recent review). Although the serotonin system may be even harder to study than the DA system due to its widespread and complicated projections, more work on the interactions of these systems is necessary to develop a mechanistic understanding of age differences in cognition–motivation interactions. Method-wise, recent studies that applied TMS over the frontal cortex to affect task-related striatal activity (e.g., van Schouwenburg et al., 2012) and dopamine release in the caudate nucleus (Strafella et al., 2001) suggest that applying noninvasive brain stimulations to regulate the frontal-striatal circuitry might potentially be another mean for investigating lifespan development of the interplays between cognition and motivation. </sup></sub>|
| Towards a mechanistic understanding of age-related changes in learning and decision making: A neuro-computational approach. (**2015**), Book Chapter.| <sub><sup> In the current chapter, the authors concentrate on the psychological and neurophysiological underpinnings of age-related deficits in decision making tasks in which the expected value of choice options has to be learned. The authors outline the relationship between age- related changes in the dopamine (DA) system as well as functional changes in subcortical and prefrontal networks involved in making decisions from experience. Furthermore, the authors will focus on potential links between neuro-computational theories of reinforcement learning and age-related deficits in experience-driven decision making. Finally, the authors conclude with a summary of the current research, identify gaps that need to be filled in the future, and provide evidence for potential targets for interventions that aim at improving learning and decision making abilities in old age. </sup></sub>|
| Age-related prefrontal impairments implicate deficient prediction of future reward in older adults. (**2015**), Article.| <sub><sup> Foresighted decision-making depends on the ability to learn the value of future outcomes and the sequential choices necessary to achieve them. Using a 3-stage Markov decision task and functional magnetic resonance imaging, we investigated age differences in the ability to extract state transition structures while learning to predict future reward. In younger adults learning was associated with enhanced activity in the prefrontal cortex (PFC). In older adults (OA) we found no evidence for PFC recruitment. However, high-performing OA showed enhanced striatal activity, suggesting that they may engage in a model-free (experience-based) learning strategy. Change point analyses revealed that in younger adults learning was characterized by distinct and abrupt shifts in PFC activity, which were predictive of behavioral change points. In OA PFC activity was less pronounced and not predictive of behavior. Our findings suggest that age-related impairments in learning future reward value can be attributed to a deficit in extracting sequential state transition structures. This deficit may lead to myopic decisions in OA if contextual information has to be temporally integrated. </sup></sub>|
| Reward speeds up and increases consistency of visual selective attention: A lifespan comparison. (**2014**), Article.| <sub><sup> Children and older adults often show less favorable reward-based learning and decision making, relative to younger adults. It is unknown, however, whether reward-based processes that influence relatively early perceptual and attentional processes show similar lifespan differences. In this study, we investigated whether stimulus'reward associations affect selective visual attention differently across the human lifespan. Children, adolescents, younger adults, and older adults performed a visual search task in which the target colors were associated with either high or low monetary rewards. We discovered that high reward value speeded up response times across all four age groups, indicating that reward modulates attentional selection across the lifespan. This speed-up in response time was largest in younger adults, relative to the other three age groups. Furthermore, only younger adults benefited from high reward value in increasing response consistency (i.e., reduction of trial-by-trial reaction time variability). Our findings suggest that reward-based modulations of relatively early and implicit perceptual and attentional processes are operative across the lifespan, and the effects appear to be greater in adulthood. The age-specific effect of reward on reducing intraindividual response variability in younger adults likely reflects mechanisms underlying the development and aging of reward processing, such as lifespan age differences in the efficacy of dopaminergic modulation. Overall, the present results indicate that reward shapes visual perception across different age groups by biasing attention to motivationally salient events. </sup></sub>|
| Reduced striatal responses to reward prediction errors in older compared with younger adults. (**2013**), Article.| <sub><sup> We examined whether older adults differ from younger adults in how they learn from rewarding and aversive outcomes. Human participants were asked to either learn to choose actions that lead to monetary reward or learn to avoid actions that lead to monetary losses. To examine age differences in the neurophysiological mechanisms of learning, we applied a combination of computational modeling and fMRI. Behavioral results showed age-related impairments in learning from reward but not in learning from monetary losses. Consistent with these results, we observed age-related reductions in BOLD activity during learning from reward in the ventromedial PFC. Furthermore, the model-based fMRI analysis revealed a reduced responsivity of the ventral striatum to reward prediction errors during learning in older than younger adults. This age-related reduction in striatal sensitivity to reward prediction errors may result from a decline in phasic dopaminergic learning signals in the elderly. </sup></sub>|
| Of goals and habits: age-related and individual differences in goal-directed decision-making. (**2013**), Article.| <sub><sup> In this study we investigated age-related and individual differences in habitual (model-free) and goal-directed (model-based) decision-making. Specifically, we were interested in three questions. First, does age affect the balance between model-based and model-free decision mechanisms? Second, are these age-related changes due to age differences in working memory (WM) capacity? Third, can model-based behavior be affected by manipulating the distinctiveness of the reward value of choice options? To answer these questions we used a two-stage Markov decision task in in combination with computational modeling to dissociate model-based and model-free decision mechanisms. To affect model-based behavior in this task we manipulated the distinctiveness of reward probabilities of choice options. The results show age-related deficits in model-based decision-making, which are particularly pronounced if unexpected reward indicates the need for a shift in decision strategy. In this situation younger adults explore the task structure, whereas older adults show perseverative behavior. Consistent with previous findings, these results indicate that older adults have deficits in the representation and updating of expected reward value. We also observed substantial individual differences in model-based behavior. In younger adults high WM capacity is associated with greater model-based behavior and this effect is further elevated when reward probabilities are more distinct. However, in older adults we found no effect of WM capacity. Moreover, age differences in model-based behavior remained statistically significant, even after controlling for WM capacity. Thus, factors other than decline in WM, such as deficits in the in the integration of expected reward value into strategic decisions may contribute to the observed impairments in model-based behavior in older adults. </sup></sub>|
|  Dopaminergic and prefrontal contributions to reward-based learning and outcome monitoring during child development and aging. (**2012**), Article.| <sub><sup> In many instances, children and older adults show similar difficulties in reward-based learning and outcome monitoring. These impairments are most pronounced in situations in which reward is uncertain (e.g., probabilistic reward schedules) and if outcome information is ambiguous (e.g., the relative value of outcomes has to be learned). Furthermore, whereas children show a greater sensitivity to external outcome information, older adults focus less on a rapid differentiation of rewarding outcomes. In this article, we review evidence for the idea that these phenomenologically similar impairments in learning and outcome monitoring in children and older adults can be attributed to deficits in different underlying neurophysiological mechanisms. We propose that in older adults learning impairments are the result of reduced dopaminergic projections to the ventromedial prefrontal cortex, which lead to less differentiated representations of reward value. In contrast, in children, impairments in learning can be primarily attributed to deficits in executive control, which may be due to a protracted development of the dorsal medial and lateral prefrontal cortices. We think that this framework maps well onto recent neurophysiological models of reward processing and is plausible from a broader developmental perspective. </sup></sub>|
| Reduced sensitivity to immediate reward during decision-making in older than younger adults. (**2012**), Article.| <sub><sup> We examined whether older adults differ from younger adults in the degree to which they favor immediate over delayed rewards during decision-making. To examine the neural correlates of age-related differences in delay discounting we acquired functional MR images while participants made decisions between smaller but sooner and larger but later monetary rewards. The behavioral results show age-related reductions in delay discounting. Less impulsive decision-making in older adults was associated with lower ventral striatal activations to immediate reward. Furthermore, older adults showed an overall higher percentage of delayed choices and reduced activity in the dorsal striatum than younger adults. This points to a reduced reward sensitivity of the dorsal striatum in older adults. Taken together, our findings indicate that less impulsive decision-making in older adults is due to a reduced sensitivity of striatal areas to reward. These age-related changes in reward sensitivity may result from transformations in dopaminergic neuromodulation with age. </sup></sub>|
| To choose or to avoid: age differences in learning from positive and negative feedback. (**2011**), Article.| <sub><sup> In this study, we investigated whether older adults learn more from bad than good choices than younger adults and whether this is reflected in the error-related negativity (ERN). We applied a feedback-based learning task with two learning conditions. In the positive learning condition, participants could learn to choose responses that lead to monetary gains, whereas in the negative learning condition, they could learn to avoid responses that lead to monetary losses. To test the stability of learning preferences, the task involved a reversal phase in which stimulus'response assignments were inverted. Negative learners were defined as individuals that performed better in the negative than in the positive learning condition (and vice versa for positive learners). The behavioral data showed strong individual differences in learning from positive and negative outcomes that persisted throughout the reversal phase and were more pronounced for older than younger adults. Older negative learners showed a stronger tendency to avoid negative outcomes than younger negative learners. However, contrary to younger adults, this negative learning bias was not associated with a larger ERN, suggesting that avoidance learning in older negative learners might be decoupled from error processing. Furthermore, older adults showed learning impairments compared to younger adults. The ERP analyses suggest that these impairments reflect deficits in the ability to build up relational representations of ambiguous outcomes. </sup></sub>|
| Younger but not older adults benefit from salient feedback during learning. (**2011**), Article.| <sub><sup> Older adults are impaired in reinforcement learning (RL) when feedback is partially ambiguous (e.g., Eppinger and Kray, 2011). In this study we examined whether older adults benefit from salient feedback information during learning. We used an electrophysiological approach and investigated 15 younger and 15 older adults with a RL task in which they had to learn stimulus'response associations under two learning conditions. In the positive learning conditions, participants could gain 50 Cents for a correct response but did not gain or lose money (00 Cent) for an incorrect response. In negative learning conditions, they could lose 50 Cents for an incorrect response but did not gain or lose money (00 Cent) for a correct response. As the identical outcome ‚Äú00 Cent‚Äù is either better or worse than the alternative outcome depending on the learning condition, this feedback type is ambiguous. To examine the influence of feedback salience we compared this condition with a condition in which positive and negative outcomes were color-coded and thereby clearly separable. The behavioral results indicated that younger adults reached higher accuracy levels under salient feedback conditions. Moreover, the error-related negativity and the feedback-related negativity for losses were larger if the good'bad dimension of feedback was salient. Hence, in younger adults salient feedback facilitates the rapid evaluation of outcomes on a good'bad dimension and by this supports learning. In contrast, for older adults we obtained neither behavioral nor electrophysiological effects of feedback salience. The older adults'performance monitoring system therefore appears less flexible in integrating additional information in this evaluation process. </sup></sub>|
| Neuromodulation of reward-based learning and decision making in human aging.  (**2011**), Article.| <sub><sup> In this paper, we review the current literature to highlight relations between age-associated declines in dopaminergic and serotonergic neuromodulation and adult age differences in adaptive goal-directed behavior. Specifically, we focus on evidence suggesting that deficits in neuromodulation contribute to older adults’ behavioral disadvantages in learning and decision making. These deficits are particularly pronounced when reward information is uncertain or the task context requires flexible adaptations to changing stimulus–reward contingencies. Moreover, emerging evidence points to age-related differences in the sensitivity to rewarding and aversive outcomes during learning and decision making if the acquisition of behavior critically depends on outcome processing. These age-related asymmetries in outcome valuation may be explained by age differences in the interplay of dopaminergic and serotonergic neuromodulation. This hypothesis is based on recent neurocomputational and psychopharmacological approaches, which suggest that dopamine and serotonin serve opponent roles in regulating the balance between approach behavior and inhibitory control. Studying adaptive regulation of behavior across the adult life span may shed new light on how the aging brain changes functionally in response to its diminishing resources. </sup></sub>|
| We remember the good things: Age differences in learning and memory. (**2010**), Article.| <sub><sup> We combined a feedback-based learning task with a recognition memory paradigm to investigate how reward-based learning affects the event-related potential (ERP) correlates of recognition memory in younger and older adults. We found that positive, but not negative learning improves memory and results in an increased early ERP old'new effect, which is typically associated with familiarity-based memory. This indicates that reward-based learning supports a fast and relatively automatic memory retrieval process. Furthermore, we found age-related impairments in reward-based learning, whereas memory for the learned information was intact in the elderly, suggesting that declarative memory might be less affected by aging.  </sup></sub>|
| An event-related potential (ERP) approach to study cognitive control processes. (**2009**), Book Chapter.| <sub><sup> The flexible adaptation to changes in the environment is one important feature of intelligent behaviour and is associated with the ability to efficiently control one's own processing. Cognitive control refers to the ability to guide thoughts and actions in accord with internal task goals. Controlling one's own behaviour is particularly required in situations that involve the flexible switching between multiple tasks, the selection and maintenance of task-relevant and the inhibition of taskirrelevant information, as well as the monitoring of error and conflict information (e.g. [22, 42, 47]). </sup></sub>|
| Developmental differences in learning and error processing: evidence from ERPs. (**2009**), Article.| <sub><sup> This study examined developmental differences in the ERP correlates of internal and external error processing (ERN and FRN) during learning. A probabilistic learning task was applied in which feedback validity was manipulated. The behavioral data showed similar accuracy for children and adults when feedback was valid, whereas age differences were obtained when it was partially invalid. We found no reduction of the ERN for children compared to adults when performance levels were equated. Yet, contrary to adults, children did not differentiate between responses when feedback was partially invalid, indicating that they are less able to represent the correctness of a response when there is interference during learning. Moreover, we found a larger FRN and reduced ERP learning effects for positive feedback for children, suggesting that they are more sensitive to external error feedback and less able to disengage from positive feedback during learning. </sup></sub>|
| Better or worse than expected? Aging, learning, and the ERN. (**2008**), Article.| <sub><sup>  This study examined age differences in error processing and reinforcement learning. We were interested in whether the electrophysiological correlates of error processing, the error-related negativity (ERN) and the feedback-related negativity (FRN), reflect learning-related changes in younger and older adults. To do so, we applied a probabilistic learning task in which we manipulated the validity of feedback. The results of our study showed that learning-related changes were much more pronounced (a) in a response-locked positivity for correct trials compared to the ERN and (b) in a feedback-locked positivity for positive feedback compared to the FRN. These findings provide an important extension to recent theoretical accounts [Holroyd, C. B., & Coles, M. G. H. (2002). The neural basis of human error processing: Reinforcement learning, dopamine, and the error-related negativity. Psychological Review, 109, 679-709; Nieuwenhuis, S., Ridderinkhof, K. R., Talsma, D., Coles, M. G. H., Holroyd, C. B., Kok, A., et al. (2002). A computational account of altered error processing in older age: Dopamine and the error-related negativity. Cognitive, Affective and Behavioral Neuroscience, 2, 19-36] since they suggest that positive learning signals on correct trials contribute to the reward-related variance in the response- and feedback-locked ERPs. This effect has been overlooked in previous studies that have focused on the role of errors and negative feedback for learning. Importantly, we did not find evidence for an age-related reduction of the ERN, when controlling for performance differences between age groups, which questions the view that older adults are generally impaired in error processing. Finally, we observed a substantial reduction of the FRN in the elderly, which indicates that older adults are less affected by negative feedback and rely more on positive feedback during learning. This finding points to an age-related asymmetry in the processing of feedback valence. </sup></sub>|
| Age differences in task switching and response monitoring: Evidence from ERPs. (**2007**), Article.| <sub><sup> This study investigates age differences in the flexible adaptation to changing demands on task switching and conflict processing. We applied a cued task-switching version of the Stroop task and manipulated the ratio of conflict trials. During task preparation, the P300 varied as a function of conflict ratio and a later positive component was larger for switch than non-switch trials. Stimulus-related conflict processing as indicated by a negativity for incompatible trials (Ni) was delayed for older adults. Moreover, the Ni varied as a function of conflict ratio and was larger for switch than for non-switch trials. Age differences were also obtained in the correct response negativity (CRN). CRN was larger on incompatible trials and this CRN-compatibility effect was enhanced when incompatible trials were infrequent in younger, but not in older adults. Our findings suggest impairments of older adults primarily in response-related conflict processing and in the flexible adaptation to changing task contexts. </sup></sub>|
| Effects of associative learning on age differences in task-set switching. (**2006**), Article.| <sub><sup> Costs of switching between tasks may disappear when subjects are able to learn associations between tasks, stimuli, and responses (cf. Rogers, R. D., & Monsell, S. (1995). Costs of a predictable switch between simple cognitive tasks. Journal of Experimental Psychology: General, 124, 207–231). The first aim of this study was to examine this possibility by manipulating stimulus-set size. We expected that costs of switching between tasks would be strongly reduced under conditions of small stimulus-set sizes (n = 4) as compared to large stimulus-set sizes (n = 96) with increasing time on task. The second aim was to determine whether younger as well as older adults were able to create associations between task components. As age differences in task switching are often found to be larger when response mappings are incompatible we also investigated interactions with response compatibility. Results of our study indicated that practice effects on switch costs were much more pronounced for small than large stimulus-set sizes, consistent with the view that the strength of associations between task components facilitates task switching. Furthermore, we found that practice benefits on task switching for small stimulus-set sizes were sensitive to age and response compatibility. In contrast to younger adults, who showed a reduction of switch costs for both response mapping conditions, older adults showed a reduction of switch costs only when response mappings were compatible. That is, older adults showed less associative learning when the currently irrelevant task feature had to be suppressed, supporting the view that older adults have primarily problems in separating overlapping task-set representations. </sup></sub>|
| Age differences in attentional control: An event‐related potential approach. (**2005**), Article.| <sub><sup> We examined age differences in event-related potentials (ERPs) associated with attentional control of task-set selection and response interference by means of a cue-based switching paradigm in which participants performed the color or word Stroop task. The results of ERPs in the cue interval indicated that P3 latencies were slowed for older adults, suggesting age-related slowing in updating currently relevant task sets. Older adults also showed a larger CNV under switching than nonswitching conditions, indicating age differences in maintaining task sets over longer periods of time. The results of target-locked ERPs revealed a negativity to incompatible Stroop trials (Ni) that was prolonged for older adults, suggesting age differences in early conflict processing. Response-locked ERPs showed a negative deflection to incompatible Stroop trials (CRN) only for younger adults, suggesting age differences also in response-related conflict processing. </sup></sub>|